import type { Photo } from '@/app/_types/photo.types';

export const mockPhoto: Photo = {
  id: 'abc123',
  slug: 'test-photo',
  alt_description: 'A beautiful job interview photo',
  description: null,
  color: '#f3f3f3',
  blur_hash: 'LGF5]+Yk^6#M@-5c,1J5@[or[Q6.',
  width: 4000,
  height: 3000,
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
  promoted_at: null,
  liked_by_user: false,
  bookmarked: false,
  likes: 10,
  asset_type: 'photo',
  breadcrumbs: [],
  current_user_collections: [],
  sponsorship: null,
  topic_submissions: {},
  alternative_slugs: {
    en: 'test-photo',
    es: 'test-photo',
    ja: 'test-photo',
    fr: 'test-photo',
    it: 'test-photo',
    ko: 'test-photo',
    de: 'test-photo',
    pt: 'test-photo',
    id: 'test-photo',
  },
  urls: {
    raw: 'https://images.unsplash.com/raw',
    full: 'https://images.unsplash.com/full',
    regular: 'https://images.unsplash.com/regular',
    small: 'https://images.unsplash.com/small',
    thumb: 'https://images.unsplash.com/thumb',
    small_s3: 'https://images.unsplash.com/small_s3',
  },
  links: {
    self: 'https://api.unsplash.com/photos/abc123',
    html: 'https://unsplash.com/photos/abc123',
    download: 'https://unsplash.com/photos/abc123/download',
    download_location: 'https://api.unsplash.com/photos/abc123/download',
  },
  user: {
    id: 'user123',
    username: 'testuser',
    name: 'Test User',
    first_name: 'Test',
    last_name: 'User',
    bio: null,
    location: null,
    portfolio_url: null,
    twitter_username: null,
    instagram_username: null,
    updated_at: '2024-01-01T00:00:00Z',
    accepted_tos: true,
    for_hire: false,
    total_collections: 0,
    total_likes: 0,
    total_photos: 10,
    total_free_photos: 10,
    total_promoted_photos: 0,
    total_illustrations: 0,
    total_free_illustrations: 0,
    total_promoted_illustrations: 0,
    links: {
      self: 'https://api.unsplash.com/users/testuser',
      html: 'https://unsplash.com/@testuser',
      photos: 'https://api.unsplash.com/users/testuser/photos',
      likes: 'https://api.unsplash.com/users/testuser/likes',
      portfolio: 'https://api.unsplash.com/users/testuser/portfolio',
    },
    profile_image: {
      small: 'https://images.unsplash.com/profile-small',
      medium: 'https://images.unsplash.com/profile-medium',
      large: 'https://images.unsplash.com/profile-large',
    },
    social: {
      instagram_username: null,
      portfolio_url: null,
      twitter_username: null,
      paypal_email: null,
    },
  },
};
